
global:
  namespace: default
name: nodejstemplate
replicaCount: 1
image:
  repository: casaacr01.azurecr.io/nodejstemplate
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.5"
ContainerPort: 9001
service:
  type: ClusterIP
  port: 80
env:
  APP_PORT: "9001"
  SWAGGER_ENABLE: "true"
