apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.ContainerPort }}
          env:
            - name: SWAGGER_ENABLE
              value: "{{ .Values.env.SWAGGER_ENABLE }}"
            - name: PORT
              value: "{{ .Values.env.APP_PORT }}"