apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejstemplate.fullname" . }}
  labels:
    {{- include "nodejstemplate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.ContainerPort }}
      protocol: TCP
      name: http

